Repository boostcamp-2020/Project17-C-Map, pull requests merged in 2020-12, with the labels that each got.

#45 Quadtree 코드 리뷰 반영
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
Labels: refactor

#46 클러스터링 검증 - DBI 계산 클래스 추가
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/DBI.swift
  Project17-C-Map/InteractiveClusteringMapTests/DBITests.swift
Labels: clustering, feat, test

#52 지도에 지워져야 할 마커 사라지지 않는 문제 해결
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: bug, clustering, fix

#49 CoreDataStack 클래스의 DispatchQueue(serial async)에서 동작하는 fetch 메서드 구현 및 Core data Entity 재설계
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/Model.xcdatamodeld/.xccurrentversion
  Project17-C-Map/InteractiveClusteringMap/CoreData/Model.xcdatamodeld/InteractiveClusteringMap.xcdatamodel/contents
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIEntity+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIEntity+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Model.xcdatamodeld/InteractiveClusteringMap.xcdatamodel/contents
  Project17-C-Map/InteractiveClusteringMap/VO/POI.swift
  Project17-C-Map/InteractiveClusteringMap/VO/POIInfo.swift
  Project17-C-Map/InteractiveClusteringMapTests/CoreDataStackTests.swift
Labels: data, feat, refactor

#53 ClusteringMarkerLayer 추가 및 Fade In/Out Animation 구현
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/MarkerTextLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/TranparentLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, refactor

#55 3주차 코드 프리징
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/xcshareddata/xcbaselines/37EB733D2562592900AC44D6.xcbaseline/F5E5C7C8-6624-4273-A05A-F99A4975DE91.plist
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/xcshareddata/xcbaselines/37EB733D2562592900AC44D6.xcbaseline/Info.plist
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/MarkerTextLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/TranparentLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/ClusteringServicing.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/Centroids/BallCutCentroidGenerator.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/Centroids/RandomCentroidGenerator.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/Centroids/ScreenCentroidGenerator.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KCoefficient.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KMeans.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KMeansValidateService.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/Metrics/Degree.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/Metrics/Quadrant.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTree.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/Model.xcdatamodeld/.xccurrentversion
  Project17-C-Map/InteractiveClusteringMap/CoreData/Model.xcdatamodeld/InteractiveClusteringMap.xcdatamodel/contents
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIEntity+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIEntity+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/DBI.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Model.xcdatamodeld/InteractiveClusteringMap.xcdatamodel/contents
  Project17-C-Map/InteractiveClusteringMap/Util/Array+Subscript.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Clusters.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Coordinate.swift
  Project17-C-Map/InteractiveClusteringMap/VO/POI.swift
  Project17-C-Map/InteractiveClusteringMap/VO/POIInfo.swift
  Project17-C-Map/InteractiveClusteringMapTests/CoreDataStackTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/DBITests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KDefineTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KDefineTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KMeansCentroidsTest.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KMeansPerformanceTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KMeansTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/BoundingBoxTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/Mockup.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/QuadTreeServiceTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/QuadTreeTests.swift
Labels: UI, clustering, data, feat

#54 Core data child context 추가 및 CRUD 메서드 작성
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/Model.xcdatamodeld/InteractiveClusteringMap.xcdatamodel/contents
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POICoordinateMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Coordinate.swift
Labels: data, feat, refactor

#57 POIService 클래스 CRUD 메서드 작성
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIInfoMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataClass.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
Labels: data, feat

#59 Concurrent 방식의 QuadTree 생성
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
Labels: clustering, feat, refactor

#58 마커 추가/삭제 윈도우 구현
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapAlertController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#62 마커 생성시 transform scale 애니매이션 적용
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/MarkerTextLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#66 롱 터치 삭제 이벤트 받기
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/LeafNodeMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#67 QuadTree 저장
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTree.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
Labels: clustering, data, refactor

#71 코드 리팩토링 및 개선 시도
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
Labels: clustering, refactor, test

#73 Quad tree remove 구현, QuadTreeServiceTests 수정
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTree.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/QuadTreeServiceTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/QuadTreeTests.swift
Labels: feat, fix, test

#74 Interactive Marker 클릭시 줌 이동
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/TranparentLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KMeans.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Cluster.swift
Labels: UI, feat

#75 클러스터 뜨기 직전에 화면 멈추는 것 수정
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
Labels: bug, fix

#72 마커 edit 애니메이션 및 버그 수정, presenter에서 해당 마커 삭제
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/ClusteringServicing.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KMeansValidateService.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/Map/LeafNodeMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapAlertController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Util/Array+.swift
  Project17-C-Map/InteractiveClusteringMap/Util/Array+Subscript.swift
Labels: UI, feat

#76 [Fix] 처음 실행 시, 클러스터링 표시 안되는 버그 수정
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
Labels: clustering, fix, refactor

#79 Interative Marker 터치시 애니메이션 적용
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#80 customInfoWindow 파일 추가
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow11.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow11.imageset/imgInfowindow11.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow11.imageset/imgInfowindow11@2x.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow11.imageset/imgInfowindow11@3x.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow12.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow12.imageset/imgInfowindow12.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow12.imageset/imgInfowindow12@2x.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow12.imageset/imgInfowindow12@3x.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow13.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow13.imageset/imgInfowindow13.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow13.imageset/imgInfowindow13@2x.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/imgInfowindow13.imageset/imgInfowindow13@3x.png
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindow.swift
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindow.xib
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindowDataSource.swift
Labels: UI, feat

#81 마커 삭제 시 layer 가 그대로 남아있던 버그 수정
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, bug, fix

#82 [fix] 최상위에서 클러스터 터치시 줌 안되던 버그 수정
  Project17-C-Map/InteractiveClusteringMap/Animation/InteractiveMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Cluster.swift
Labels: UI, bug, fix

#83 [fix] 최상단에서 애니메이션이 계속되던 버그 수정
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, bug, fix

#84 [fix] 마커 edit 시 layer 잔상 버그 수정
  Project17-C-Map/InteractiveClusteringMap/Animation/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Map/LeafNodeMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, bug, fix

#85 customWindow 연결
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindow.swift
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindow.xib
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindowDataSource.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#86 지도 롱 터치 시 마커 추가 기능 추가
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/NMFMarker+.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/ClusteringServicing.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/KMeansValidateService.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapAlertController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/NMGLatLngBounds+BoundingBox.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
Labels: UI, feat

#89 맵 인터렉션 설정
  Project17-C-Map/InteractiveClusteringMap/Animation/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/1024.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/114.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/120.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/180.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/29.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/40.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/57.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/58.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/60.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/80.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/87.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/TreeDataStore.swift
Labels: UI, feat

#91 launch screen 생성
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/AppDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/MapC.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/MapC.imageset/KakaoTalk_Photo_2020-12-10-01-05-55.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/background.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/background.imageset/background.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/globe.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/globe.imageset/globe.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/marker.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/marker.imageset/KakaoTalk_Photo_2020-12-09-19-38-52-1.png
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/LaunchScreen.storyboard
  Project17-C-Map/InteractiveClusteringMap/BlackOpsOne_Regular.ttf
  Project17-C-Map/InteractiveClusteringMap/Info.plist
  Project17-C-Map/InteractiveClusteringMap/Launch/Base.lproj/LaunchScreen.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/Splash.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/SplashViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Launch/UIImage+.swift
  Project17-C-Map/InteractiveClusteringMap/SceneDelegate.swift
Labels: UI, feat

#90 POI 목록 화면 구현
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/defaultImg.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/defaultImg.imageset/defaultImg.png
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/Main.storyboard
  Project17-C-Map/InteractiveClusteringMap/Clustering/KMeans/DBI.swift
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/TreeDataStore.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Extension/FileManager+.swift
  Project17-C-Map/InteractiveClusteringMap/Extension/URL+Image.swift
  Project17-C-Map/InteractiveClusteringMap/Info.plist
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController+PanGesture.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Network/DataError.swift
  Project17-C-Map/InteractiveClusteringMap/Network/DataProvider.swift
  Project17-C-Map/InteractiveClusteringMap/Network/GeocodingNetwork.swift
  Project17-C-Map/InteractiveClusteringMap/Network/ImageProvider.swift
  Project17-C-Map/InteractiveClusteringMap/Network/PlaceInfoService.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Geocoding.swift
  Project17-C-Map/InteractiveClusteringMap/VO/POIInfo.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Place.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Places.swift
  Project17-C-Map/InteractiveClusteringMap/View/FilterButton.swift
  Project17-C-Map/InteractiveClusteringMap/View/FilterScrollView.swift
  Project17-C-Map/InteractiveClusteringMap/View/PlaceCell.swift
  Project17-C-Map/InteractiveClusteringMap/View/PlaceHeaderView.swift
  Project17-C-Map/InteractiveClusteringMap/View/UIView+Attributes.swift
Labels: UI, feat, refactor

#96 splashView Loading UILabel 추가
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/fiftyColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/fiveThousandColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/globe.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/globe.imageset/globe.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/globe.imageset/globe_of_asia_pacific_region-removebg-preview.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/hundredColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/marker.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/marker.imageset/KakaoTalk_Photo_2020-12-09-01-25-10.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/marker.imageset/KakaoTalk_Photo_2020-12-09-19-38-52-1.png
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/overFiveThousandColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/thousandColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Launch/Base.lproj/LaunchScreen.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/Splash.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/SplashViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Launch/UIImage+.swift
  Project17-C-Map/InteractiveClusteringMap/Launch/UILabel+.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#101 [fix] memory leak 수정 및 버튼 카메라 줌 이동시 애니메이션 취소
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController+PanGesture.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController.swift
  Project17-C-Map/InteractiveClusteringMap/View/UIView+Attributes.swift
Labels: bug, fix

#103 [fix] marker infowindow constraint 수정
  Project17-C-Map/InteractiveClusteringMap/Map/CustomInfoWindow.xib
Labels: UI, bug, fix

#104 클러스터링 영역 표시
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/polygon.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/Main.storyboard
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
Labels: UI, feat

#106 color Asset 색상으로 변경
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarkerLayer.swift
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/fiftyColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/fiveThousandColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/hundredColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/overFiveThousandColor.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/LaunchScreen/thousandColor.colorset/Contents.json
Labels: UI, feat

#109 [fix] gif 이미지 수정
  README.md
Labels: docs, fix

#111 CoreDataStack 생성 시 데이터를 가져오지 않고 갯수만 가져오도록 수정
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
Labels: data, fix

#107 POI 정보 목록 화면 구현
  Project17-C-Map/InteractiveClusteringMap/Animation/AnimationController.swift
  Project17-C-Map/InteractiveClusteringMap/Animation/ClusteringMarker.swift
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/Main.storyboard
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/TreeDataStore.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController+PanGesture.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Network/PlaceInfoService.swift
  Project17-C-Map/InteractiveClusteringMap/View/FilterScrollView.swift
Labels: UI, feat

#112 Onboarding 화면 구현
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Animation/NMFMarker+.swift
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/deepBlue.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/greenCyan.colorset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/onboarding.imageset/Contents.json
  Project17-C-Map/InteractiveClusteringMap/Assets.xcassets/onboarding.imageset/Image.png
  Project17-C-Map/InteractiveClusteringMap/Extension/Array+.swift
  Project17-C-Map/InteractiveClusteringMap/Extension/UIColor+.swift
  Project17-C-Map/InteractiveClusteringMap/Launch/SplashViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/NMGLatLngBounds+BoundingBox.swift
  Project17-C-Map/InteractiveClusteringMap/Onboarding/Onboarding.storyboard
  Project17-C-Map/InteractiveClusteringMap/Onboarding/OnboardingViewController.swift
  Project17-C-Map/InteractiveClusteringMap/SceneDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Util/UserDefaultsManager.swift
Labels: UI, feat

#116 하단 POI 정보 목록 화면 수정
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/Main.storyboard
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController+PanGesture.swift
  Project17-C-Map/InteractiveClusteringMap/Map/PlaceListViewController.swift
Labels: bug, fix

#121 [fix] 이동 후 마커 생성시, 지도가 끊기던 문제
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
Labels: fix, refactor

#123 애니메이션 시 화면에 남는 잔상 제거
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Extension/UILabel+.swift
  Project17-C-Map/InteractiveClusteringMap/Launch/Base.lproj/LaunchScreen.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/Splash.storyboard
  Project17-C-Map/InteractiveClusteringMap/Launch/SplashViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/UI/View/Map/InteractiveMapView.swift
Labels: UI, fix

#124 클러스터 Polygon 영역 재설정
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
Labels: fix

#127 하단 POI 목록 화면 셀 눌렀을 때, 목록 화면 작아지게 수정
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/PlaceListViewController+PanGesture.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/PlaceListViewController.swift
Labels: fix

#130 하단 뷰 Invaild Section 문제 나던 것 해결
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/PlaceListViewController.swift
Labels: bug, fix

#131 줌 레벨 21 초과 시 리프노드 마커로 표시
  Project17-C-Map/InteractiveClusteringMap/Clustering/QuadTree/QuadTreeClusteringService.swift
  Project17-C-Map/InteractiveClusteringMap/Info.plist
Labels: UI, clustering, feat

#132 [feat] 마커 추가 시 카테고리 추가
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
Labels: data, feat

#135 Core data persistent store 에러 핸들링 처리
  Project17-C-Map/InteractiveClusteringMap/AppDelegate.swift
Labels: data, fix

#137 마커 토스트 추가 및 playButton 추가
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/Base.lproj/Main.storyboard
  Project17-C-Map/InteractiveClusteringMap/Extension/ViewController+Toast.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/UI/View/Map/InteractiveMapView.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
Labels: fix

#136 하단 POI 목록 화면 버벅이던 문제
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController+NMFMapViewCameraDelegate.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/PlaceListViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Network/PlaceInfoService.swift
Labels: fix

#138 edit mode 시 플레이 버튼 비활성화
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
Labels: fix

#140 테스트 수정, 삭제 취소시 탭 안되던 것 수정, 리팩토링
  Project17-C-Map/InteractiveClusteringMap.xcodeproj/project.pbxproj
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/DataManagable.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POI/POIMO+CoreDataProperties.swift
  Project17-C-Map/InteractiveClusteringMap/CoreData/POIService.swift
  Project17-C-Map/InteractiveClusteringMap/Extension/NMFMarker+Animation.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ClusterInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/MapPresenter.swift
  Project17-C-Map/InteractiveClusteringMap/Map/POIDataInteractor.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController+PlaceListView.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/PlaceListViewController.swift
  Project17-C-Map/InteractiveClusteringMap/Network/PlaceInfoService.swift
  Project17-C-Map/InteractiveClusteringMap/UI/Marker/ClusteringMarker.swift
  Project17-C-Map/InteractiveClusteringMap/UI/Marker/LeafNodeMarker.swift
  Project17-C-Map/InteractiveClusteringMap/UI/Marker/Markable.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox+NMFLatLng.swift
  Project17-C-Map/InteractiveClusteringMap/VO/BoundingBox.swift
  Project17-C-Map/InteractiveClusteringMap/VO/Coordinate.swift
  Project17-C-Map/InteractiveClusteringMapTests/DBITests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KDefineTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KMeansPerformanceTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/KMeans/KMeansTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/BoundingBoxTests.swift
  Project17-C-Map/InteractiveClusteringMapTests/QuadTreeTests/QuadTreeServiceTests.swift
Labels: fix, refactor, test

#141 core data json data init 비동기로 처리
  Project17-C-Map/InteractiveClusteringMap/CoreData/CoreDataStack.swift
Labels: data, fix

#142 플레이 버튼 버그 픽스
  Project17-C-Map/InteractiveClusteringMap/Map/ViewController/MapViewController.swift
  Project17-C-Map/InteractiveClusteringMap/UI/View/Map/InteractiveMapView.swift
Labels: UI, fix

#145 앱 디스플레이 이름 수정
  Project17-C-Map/InteractiveClusteringMap/Info.plist
Labels: fix
